kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2 
  zones: cn-northwest-1a
  iopsPerGB: "3" 
  fsType: ext4
reclaimPolicy: Retain  # Useful in case you delete the PersistentVolumeClaim
allowVolumeExpansion: true